##############################################################################
##                                                                          ##
##          GitHub : https://github.com/edokeh/spm-chaos-build              ##
##                                                                          ##
##############################################################################

build:
	cd .. && spm-chaos-build root -C ../js/modules/seajs/seajs-map/seajs-map-root.js -O ../js/modules --gzip current